### ISSUE TITLE
Publish action

### ISSUE THREAD

**Issue by saku-koodari** [saku-kaarakainen/mapline#14]
In the action:
```yml
name: Publish
run: dotnet publish --no-build --verbosity normal
working-directory: "src/mapline.web"
```

Fails, because, appearantly of the leaflet. I tried to include `npm install leaflet vue2-leaflet --save` in #13 , but it didn't seem to help
